local_backend: true

backend:
  name: github
  repo: mikegrunwald/mikegrunwald.com
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

locale: "en"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Show in Project list",
          name: "showInProjectList",
          widget: "boolean",
          default: true,
          required: false,
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Subtitle",
          name: "subtitle",
          widget: "string",
          required: false,
        }
      - { label: "Agency", name: "agency", widget: "string", required: false }
      - { label: "Partners", name: "partners", widget: "list", required: false }
      - { label: "Client", name: "client", widget: "string", required: false }
      - {
          label: "Role",
          name: "role",
          widget: "string",
          required: true,
          default: "Frontend Developer",
        }
      - { label: "Year", name: "year", widget: "number", required: false }
      - {
          label: "Tech List",
          name: "techList",
          widget: "list",
          allow_add: true,
          allow_remove: true,
          allow_reorder: true,
          field: { label: "Tech", name: "tech", widget: "string" },
          collapsed: true,
          summary: "{{field}}",
          minimize_collapsed: true,
        }
      - {
          label: "Description",
          name: "description",
          widget: "markdown",
          required: false,
        }
      - { label: "Media", name: "media", widget: "list", required: false }
      - { label: "Links", name: "links", widget: "list", required: false }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/content/pages/uses.md"
        label: "Uses Page"
        name: "uses"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "meta"
    label: "Site Settings"
    files:
      - file: "src/content/meta/site.json"
        label: "Global Site Settings"
        name: "site"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - {
              label: "Tagline",
              name: "tagline",
              widget: "string",
              required: false,
            }
          - {
              label: "Description",
              name: "description",
              widget: "text",
              required: false,
            }
