local_backend: true

backend:
  name: github
  repo: mikegrunwald/mikegrunwald.com
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

locale: "en"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", required: false }
      - {
          label: "Thumbnail",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/content/pages/uses.md"
        label: "Uses Page"
        name: "uses"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "meta"
    label: "Site Settings"
    files:
      - file: "src/content/meta/site.json"
        label: "Global Site Settings"
        name: "site"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - {
              label: "Tagline",
              name: "tagline",
              widget: "string",
              required: false,
            }
          - {
              label: "Description",
              name: "description",
              widget: "text",
              required: false,
            }
