local_backend: true

backend:
  name: github
  repo: mikegrunwald/mikegrunwald.com
  branch: main
  base_url: https://mikegrunwald.com
  auth_endpoint: auth

media_folder: "static/uploads"
public_folder: "/uploads"

locale: "en"

collections:
  - name: "work"
    label: "Work"
    folder: "src/content/work"
    create: true
    slug: "{{slug}}"
    sortable_fields: ['order', 'title', 'year']
    fields:
      - {
          label: "Show In",
          name: "showIn",
          widget: "object",
          collapsed: true,
          required: false,
          fields:
            [
              {
                label: "Featured List",
                name: "featuredList",
                widget: "boolean",
                default: true,
                required: false,
              },
              {
                label: "Work List",
                name: "workList",
                widget: "boolean",
                default: true,
                required: false,
              },
            ],
        }
      - { label: "Order", name: "order", widget: "number", default: 0, required: false }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Subtitle",
          name: "subtitle",
          widget: "string",
          required: false,
        }
      - { label: "Agency", name: "agency", widget: "string", required: false }
      - {
          label: "Partners",
          name: "partners",
          widget: "list",
          allow_add: true,
          allow_remove: true,
          allow_reorder: true,
          field: { label: "Partner", name: "partner", widget: "string" },
          collapsed: true,
          summary: "{{field}}",
          minimize_collapsed: true,
        }
      - { label: "Client", name: "client", widget: "string", required: false }
      - {
          label: "Role",
          name: "role",
          widget: "string",
          required: true,
          default: "Frontend Developer",
        }
      - { label: "Year", name: "year", widget: "number", required: false }
      - {
          label: "Media",
          name: "media",
          widget: "list",
          required: false,
          field: { label: "Media URL", name: "url", widget: "smart-media" },
        }
      - {
          label: "Description",
          name: "description",
          widget: "markdown",
          required: false,
        }
      - {
          label: "Links",
          name: "links",
          widget: "list",
          required: false,
          collapsed: true,
          field: { label: "Link", name: "linkItem", widget: "link" },
        }
      - {
          label: "Tech List",
          name: "techList",
          widget: "list",
          allow_add: true,
          allow_remove: true,
          allow_reorder: true,
          field: { label: "Tech", name: "tech", widget: "string" },
          collapsed: true,
          summary: "{{field}}",
          minimize_collapsed: true,
        }
      - {
          label: "Awards",
          name: "awards",
          widget: "list",
          required: false,
          collapsed: true,
          summary: "{{fields.awardType}} - {{fields.date}}",
          fields:
            [
              { label: "Link", name: "link", widget: "link" },
              { label: "Logo", name: "logo", widget: "image" },
              { label: "Award Type", name: "awardType", widget: "string" },
              { label: "Date", name: "date", widget: "datetime" },
            ],
        }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/content/pages/uses.md"
        label: "Uses Page"
        name: "uses"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "meta"
    label: "Site Settings"
    files:
      - file: "src/content/meta/site.json"
        label: "Global Site Settings"
        name: "site"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - {
              label: "Tagline",
              name: "tagline",
              widget: "string",
              required: false,
            }
          - {
              label: "Description",
              name: "description",
              widget: "text",
              required: false,
            }
